MAKEFLAGS += --no-print-directory

# =============================================================================
# Configuration
# =============================================================================

CXX := g++

TARGET := shelf
BUILD_DIR := build
OBJ_DIR := $(BUILD_DIR)/obj
GCOV_DIR := $(BUILD_DIR)/gcov
COVERAGE_DIR := $(BUILD_DIR)/coverage_html

DEBUG_LEVEL ?= 2

CPPFLAGS := \
	-I./include \
	-I./src/vendor/logger

CXXFLAGS := \
	-std=c++20 \
	-Wall \
	-Wextra \
	-Werror \
	-DDEBUG_LEVEL=$(DEBUG_LEVEL) \
	-MMD \
	-MP

GCOV_FLAGS := \
	-fprofile-arcs \
	-ftest-coverage \
	-O0 \
	-g

OS := $(shell uname -s)


# =============================================================================
# Sources
# =============================================================================

# All project sources except vendored code.
SRC := $(shell find src -type f -name '*.cpp' \
	-not -path 'src/vendor/*')

OBJ := $(patsubst src/%.cpp,$(OBJ_DIR)/%.o,$(SRC))
DEP := $(OBJ:.o=.d)

TEST_SRC := $(wildcard test/*.cpp)
TEST_BIN := $(GCOV_DIR)/test


# =============================================================================
# Progress bar
# =============================================================================

TERM_WIDTH := $(shell stty size 2>/dev/null | awk '{print $$2}')
TERM_WIDTH := $(if $(TERM_WIDTH),$(TERM_WIDTH),80)
BAR_WIDTH := $(shell expr $(TERM_WIDTH) \* 80 / 100 - 20)

TOTAL := $(words $(OBJ))
DONE := 0

TOTAL_GCOV := $(words $(OBJ))
DONE_GCOV := 0


define print_bar
FILLED=$$(( ($1 * $(BAR_WIDTH)) / $2 )); \
UNFILLED=$$(( $(BAR_WIDTH) - FILLED )); \
BAR=$$(printf "%0.s▓" $$(seq 1 $$FILLED)); \
SP=""; \
if [ $$UNFILLED -gt 0 ]; then \
	SP=$$(printf "%0.s░" $$(seq 1 $$UNFILLED)); \
fi; \
PCT=$$(( 100 * $1 / $2 )); \
printf "\r$3 [$$BAR$$SP] %3d%%" $$PCT; \
if [ $1 -eq $2 ]; then printf "\n"; fi
endef


# =============================================================================
# Main targets
# =============================================================================

.PHONY: all
all: $(TARGET) documentation


$(TARGET): compile_logger $(OBJ)
	@$(call print_bar,1,2,target linking:     )
	@$(CXX) $(OBJ) -L./src/vendor/logger -l:liblogger.a -o $@
	@$(call print_bar,1,1,target linking:     )


# =============================================================================
# Object files
# =============================================================================

$(OBJ_DIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	@$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@
	$(eval DONE := $(shell expr $(DONE) + 1))
	@$(call print_bar,$(DONE),$(TOTAL),target compilation: )


# Header dependencies generated by -MMD -MP
-include $(DEP)


# =============================================================================
# Debug / Release
# =============================================================================

.PHONY: debug
debug: CXXFLAGS += -g -O0
debug: clean $(TARGET)


.PHONY: release
release: CXXFLAGS += -O2 -DNDEBUG
release: clean $(TARGET)


# =============================================================================
# Example
# =============================================================================

.PHONY: example
example: $(TARGET)
	@$(call print_bar,1,2,example compilation:)
	@mkdir -p $(BUILD_DIR)
	@$(CXX) $(CPPFLAGS) $(CXXFLAGS) -g \
		-o $(BUILD_DIR)/example \
		./example/main.cpp \
		-L. -l:$(TARGET) \
		-L./src/vendor/logger -l:liblogger.a
	@$(call print_bar,1,1,example compilation:)


# =============================================================================
# Tests + coverage
# =============================================================================

.PHONY: lib_gcov
lib_gcov: compile_logger $(GCOV_OBJ)
	@$(call print_bar,1,2,gcov compilation:    )
	@mkdir -p $(GCOV_DIR)
	@ar rcs $(GCOV_DIR)/lib_gcov.a $(GCOV_OBJ)
	@$(call print_bar,1,1,gcov compilation:    )


GCOV_OBJ := $(patsubst src/%.cpp,$(GCOV_DIR)/%.o,$(SRC))
GCOV_DEP := $(GCOV_OBJ:.o=.d)


$(GCOV_DIR)/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	@$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOV_FLAGS) \
		-c $< -o $@
	$(eval DONE_GCOV := $(shell expr $(DONE_GCOV) + 1))
	@$(call print_bar,$(DONE_GCOV),$(TOTAL_GCOV),test compilation:   )


-include $(GCOV_DEP)


.PHONY: test
test: $(TEST_BIN)
	@echo
	@echo "Run tests..."
	@$(TEST_BIN) > /tmp/shelf_test.log 2>&1 || true
	@if grep -q "\[  FAILED  \]" /tmp/shelf_test.log; then \
		echo "FAIL! 💥"; \
		cat /tmp/shelf_test.log; \
	else \
		echo "SUCCESSFUL! ✅"; \
	fi
	@rm -f /tmp/shelf_test.log
	@echo


$(TEST_BIN): $(TEST_SRC) lib_gcov
	@$(call print_bar,1,2,test build:         )
	@mkdir -p $(dir $@)
	@$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(GCOV_FLAGS) \
		$(TEST_SRC) \
		-L$(GCOV_DIR) -l:lib_gcov.a \
		-L./src/vendor/logger -l:liblogger.a \
		-lgtest -lm -lpthread \
		-o $@
	@$(call print_bar,1,1,test build:         )


.PHONY: coverage
coverage: test
	@echo "Generating coverage report..."
	@mkdir -p $(COVERAGE_DIR)
	@lcov \
		--capture \
		--directory $(GCOV_DIR) \
		--ignore-errors inconsistent \
		--rc geninfo_unexecuted_blocks=1 \
		--output-file $(COVERAGE_DIR)/base.info \
		> /dev/null 2>&1
	@genhtml \
		$(COVERAGE_DIR)/base.info \
		--output-directory $(COVERAGE_DIR) \
		> /dev/null 2>&1
	@echo "Coverage report: $(COVERAGE_DIR)/index.html ✅"
	@echo


# =============================================================================
# Valgrind / leaks
# =============================================================================

.PHONY: valgrind
valgrind: $(TEST_BIN)
	@echo

	@if [ "$(OS)" = "Linux" ]; then \
		echo "Run tests via valgrind..."; \
		CK_FORK=no valgrind \
			--error-exitcode=1 \
			--tool=memcheck \
			--leak-check=yes \
			$(TEST_BIN) \
			> /tmp/shelf_valgrind.log 2>&1 || true; \
	else \
		echo "Run tests via leaks..."; \
		leaks -atExit -- $(TEST_BIN) \
			> /tmp/shelf_valgrind.log 2>&1 || true; \
	fi

	@if grep -q "ERROR SUMMARY: 0 errors" /tmp/shelf_valgrind.log; then \
		echo "SUCCESSFUL! ✅"; \
	else \
		echo "FAIL! 💥"; \
		cat /tmp/shelf_valgrind.log; \
	fi

	@rm -f /tmp/shelf_valgrind.log
	@echo


# =============================================================================
# Vendor
# =============================================================================

.PHONY: compile_logger
compile_logger:
	@$(MAKE) -C ./src/vendor/logger


# =============================================================================
# Documentation
# =============================================================================

.PHONY: documentation
documentation:
	@doxygen > /dev/null 2>&1 || true


# =============================================================================
# Compilation database
# =============================================================================

compile_commands.json:
	@bear -- make all


# =============================================================================
# Utilities
# =============================================================================

.PHONY: clean rebuild

clean:
	@rm -rf $(BUILD_DIR) $(TARGET)
	@rm -f app.log
	@$(MAKE) clean -C ./src/vendor/logger


rebuild: clean all
